name: Cypress Testing

on: [workflow_dispatch, push, pull_request]

permissions: read-all

jobs:
  Coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 14, 16, 18 ]
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Setup SQL Server
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine, sqlclient, sqlpackage

      - name: Create MonTY Database
        run: |
          sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "create database MonTY"
          sqlcmd -S localhost -U sa -P dbatools.I0 -d MonTY -i database/scripts/createTables.sql -I
      
      - name: Update NPM (Node 14)
        if: ${{ matrix.node == 14 }}
        run: npm install -g npm@7

      - name: Install Package
        run: npm ci

      - name: Copy Test Config
        run: cp ./data/config.githubActions.js ./data/config.js

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          browser: chrome